version: "2"

services:
  app:
    container_name: devops-k8s-app
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - redis
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=verysecurepassword

  redis:
    container_name: devops-k8s-redis
    image: redis:5.0.5-alpine
    command: redis-server --requirepass verysecurepassword
